import os

# Create the main app directory
os.mkdir("my-app")

# Create the subdirectories
os.mkdir("my-app/node_modules")
os.mkdir("my-app/public")
os.mkdir("my-app/src")
os.mkdir("my-app/src/components")
os.mkdir("my-app/src/containers")
os.mkdir("my-app/src/redux")
os.mkdir("my-app/src/redux/actions")
os.mkdir("my-app/src/redux/reducers")
os.mkdir("my-app/src/styles")
os.mkdir("my-app/src/utils")

# Create the files
open("my-app/public/index.html", "w").close()
open("my-app/public/favicon.ico", "w").close()
open("my-app/public/manifest.json", "w").close()
open("my-app/src/components/FormInput.js", "w").close()
open("my-app/src/components/RegionInfo.js", "w").close()
open("my-app/src/components/Map.js", "w").close()
open("my-app/src/components/Sidebar.js", "w").close()
open("my-app/src/components/Header.js", "w").close()
open("my-app/src/components/Footer.js", "w").close()
open("my-app/src/components/NightModeToggle.js", "w").close()
open("my-app/src/containers/App.js", "w").close()
open("my-app/src/redux/actions/index.js", "w").close()
open("my-app/src/redux/reducers/index.js", "w").close()
open("my-app/src/redux/store.js", "w").close()
open("my-app/src/styles/App.css", "w").close()
open("my-app/src/styles/index.css", "w").close()
open("my-app/src/styles/variables.css", "w").close()
open("my-app/src/utils/api.js", "w").close()
open("my-app/src/utils/turf.js", "w").close()
open("my-app/src/index.js", "w").close()
open("my-app/src/serviceWorker.js", "w").close()
open("my-app/src/setupTests.js", "w").close()
open("my-app/.env", "w").close()
open("my-app/.eslintignore", "w").close()
open("my-app/.eslintrc.json", "w").close()
open("my-app/.gitignore", "w").close()
open("my-app/package-lock.json", "w").close()
open("my-app/package.json", "w").close()
open("my-app/README.md", "w").close()
